[package]
name = "{{project-name}}"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
ratatui = { version = "0.30.0", features = ["all-widgets"] }
ratatui-recipe = "0.0.2"
